### ISSUE TITLE
import modules failed

### ISSUE THREAD

**Issue by erichuang2015** [jeromeludmann/domain-checker#1]
hello

I am testing this script with the test codes provided. it shows error when run check.js

it said 

(function (exports, require, module, __filename, __dirname) { import domainChecker from 'domain-checker';
SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Proxy.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at createDynamicModule (internal/modules/esm/translators.js:56:15)
    at setExecutor (internal/modules/esm/create_dynamic_module.js:50:23)

my node version is 10.10

**Comment by jeromeludmann** [comment]
Hello,

The normal use for `check.js` is to run it with `sh check.js`.
But however, there are many things that do not work (first, the path need to be fixed).

I will try fix that soon or you can make a PR if you want.

**Comment by jeromeludmann** [comment]
@erichuang2015 

A quick fix has been made.

You can now run `check.js` just by typing:

```
$ ./examples/check.js
```

Thanks for your feedback.
